databases:
  - name: geek_DB
    databaseName: geek_db
    user: geek
    region: singapore

services:
  - type: web
    name: geek
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key:  DATABASE_URL
        fromDatabase:
          name: geek_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
